#### Task 1

In [11]:
import numpy as np

# sigmoid function
def nonlin (x, deriv = False ):
    if( deriv == True ):
        return x*(1 -x)
    return 1/(1+ np. exp(-x))

# input dataset
X = np. array ([ [0 ,0 ,1] ,
                [0 ,1 ,1] ,
                [1 ,0 ,1] ,
                [1 ,1 ,1] ])

# output dataset
y = np. array ([[0 ,0 ,1 ,1]]) .True
# seed random numbers to make calculation
# deterministic ( just a good practice )
np. random . seed (1)
# initialize weights randomly with mean 0
syn0 = 2* np. random . random ((3 ,1) ) - 1
for iter in range (10000) :
    # forward propagation
    l0 = X
    l1 = nonlin (np. dot(l0 , syn0 ))
    # how much did we miss ?
    l1_error = y - l1
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin (l1 , True )
    # update weights
    syn0 += np. dot(l0.T, l1_delta )
print (" Output After Training :")
print (l1)

 Output After Training :
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


In [10]:
import numpy as np
import pandas as pd

# Sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

# Load dataset from CSV
dataset = pd.read_csv(r"diabetes.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values.reshape(-1, 1)

# Seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

# Initialize weights randomly with mean 0
syn0 = 2 * np.random.random((X.shape[1], 1)) - 1

# Training loop
for iter in range(10000):
    # Forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # Calculate error
    l1_error = y - l1

    # Update weights using gradient descent
    l1_delta = l1_error * nonlin(l1, True)
    syn0 += np.dot(l0.T, l1_delta)

# Print output after training
print("Output After Training:")
print(l1)


Output After Training:
[[1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.0

#### Task 2

In [12]:
import numpy as np

# Sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

# Input dataset
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

# Output dataset
y = np.array([[0, 1, 1, 0]]).T

# Seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

# Initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3, 1)) - 1

# Training loop
for iter in range(10000):
    # Forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # Calculate error
    l1_error = y - l1

    # Update weights using gradient descent
    l1_delta = l1_error * nonlin(l1, True)
    syn0 += np.dot(l0.T, l1_delta)

# Print output after training
print("Output After Training:")
print(l1)

Output After Training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
