In [3]:
import pandas as pd , scipy , numpy as np
from sklearn . preprocessing import MinMaxScaler
from sklearn . naive_bayes import GaussianNB
from sklearn . preprocessing import LabelEncoder

ds = pd. read_excel (r"Weather (2).xlsx")
x=ds. iloc [: ,0:2]. values #for input values
y=ds. iloc [: ,2]. values # for output value
# Import LabelEncoder
le= LabelEncoder ()
# Converting string labels into numbers .
x [: ,0]= le. fit_transform (x [: ,0])
x [: ,1]= le. fit_transform (x [: ,1])
y=le. fit_transform (y)
print (" Weather :", x[: ,0])
print (" Temp :",x [: ,1])
print (" Play :",y)
# Import Gaussian Naive Bayes model
# Create a Gaussian Classifier
model = GaussianNB ()
# Train the model using the training sets
model . fit(x,y)
# predict Output
predict = model . predict ([[0 ,1]]) # 0: Overcast , 2: Mild
print (" Predicted Value :", predict )

 Weather : [3 3 1 2 2 2 0 3 3 2 3 0 0 2]
 Temp : [1 1 1 2 0 2 0 2 0 2 2 2 1 2]
 Play : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
 Predicted Value : [1]


In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Step 1: Read data from .csv file
data = pd.read_csv(r'derm.csv')

# Assuming the last column contains the class labels and the rest are features
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Step 2: Handle Missing Values
X = X.fillna(X.mean())  # Replace missing values with the mean of the column

# Step 3: Train/Test Split
train_splits = [(0.6, 0.4), (0.7, 0.3), (0.8, 0.2)]

for train_size, test_size in train_splits:
    print(f"\nTrain/Test Split: {train_size}/{test_size}")

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, test_size=test_size, random_state=42)

    # Step 4: Train the Naïve Bayes Classifier
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)

    # Step 5: Predict and Evaluate
    y_pred = classifier.predict(X_test)

    # Calculate performance metrics suitable for multiclass classification
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    print(f"Accuracy: {accuracy:.3f}")
    print(f"Precision: {precision:.3f}")
    print(f"Recall: {recall:.3f}")
    print(f"F1-score: {f1:.3f}")

    # Step 6: Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(conf_matrix)

    # Step 7: Cross-Validation
    k = 5  # Choose a value of k for k-fold cross-validation
    scores = cross_val_score(classifier, X, y, cv=k)
    avg_accuracy = np.mean(scores)

    print(f"\nCross-Validation (k={k})")
    print(f"Average Accuracy: {avg_accuracy:.3f}")


Train/Test Split: 0.6/0.4
Accuracy: 0.878
Precision: 0.904
Recall: 0.878
F1-score: 0.860
Confusion Matrix:
[[52  0  0  0  0  0]
 [ 0  7  0 13  4  0]
 [ 0  0 27  0  0  0]
 [ 0  0  0 18  0  0]
 [ 0  1  0  0 20  0]
 [ 0  0  0  0  0  5]]

Cross-Validation (k=5)
Average Accuracy: 0.874

Train/Test Split: 0.7/0.3
Accuracy: 0.873
Precision: 0.889
Recall: 0.873
F1-score: 0.848
Confusion Matrix:
[[40  0  0  0  0  0]
 [ 0  3  0 11  2  0]
 [ 0  0 19  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  1  0  0 15  0]
 [ 0  0  0  0  0  4]]

Cross-Validation (k=5)
Average Accuracy: 0.874

Train/Test Split: 0.8/0.2
Accuracy: 0.905
Precision: 0.909
Recall: 0.905
F1-score: 0.894
Confusion Matrix:
[[31  0  0  0  0  0]
 [ 0  3  0  4  2  0]
 [ 0  0 13  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  1  0  0  9  0]
 [ 0  0  0  0  0  3]]

Cross-Validation (k=5)
Average Accuracy: 0.874


In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Step 1: Read data from .xlsx file
data = pd.read_csv(r'BankNote_Authentication.csv')

# Assuming the last column contains the class labels and the rest are features
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Step 2: Handle Missing Values
X = X.fillna(X.mean())  # Replace missing values with the mean of the column

# Step 3: Train/Test Split
train_splits = [(0.5, 0.5), (0.7, 0.3), (0.9, 0.1)]

for train_size, test_size in train_splits:
    print(f"\nTrain/Test Split: {train_size}/{test_size}")

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, test_size=test_size, random_state=42)

    # Step 4: Train the Naïve Bayes Classifier
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)

    # Step 5: Predict and Evaluate
    y_pred = classifier.predict(X_test)

    # Calculate performance metrics suitable for multiclass classification
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    print(f"Accuracy: {accuracy:.3f}")
    print(f"Precision: {precision:.3f}")
    print(f"Recall: {recall:.3f}")
    print(f"F1-score: {f1:.3f}")

    # Step 6: Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(conf_matrix)

    # Step 7: Cross-Validation
    k = 5  # Choose a value of k for k-fold cross-validation
    scores = cross_val_score(classifier, X, y, cv=k)
    avg_accuracy = np.mean(scores)

    print(f"\nCross-Validation (k={k})")
    print(f"Average Accuracy: {avg_accuracy:.3f}")


Train/Test Split: 0.5/0.5
Accuracy: 0.832
Precision: 0.832
Recall: 0.832
F1-score: 0.832
Confusion Matrix:
[[339  47]
 [ 68 232]]

Cross-Validation (k=5)
Average Accuracy: 0.838

Train/Test Split: 0.7/0.3
Accuracy: 0.837
Precision: 0.840
Recall: 0.837
F1-score: 0.836
Confusion Matrix:
[[207  22]
 [ 45 138]]

Cross-Validation (k=5)
Average Accuracy: 0.838

Train/Test Split: 0.9/0.1
Accuracy: 0.812
Precision: 0.821
Recall: 0.812
F1-score: 0.807
Confusion Matrix:
[[71  6]
 [20 41]]

Cross-Validation (k=5)
Average Accuracy: 0.838


In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score

# Step 1: Read data from CSV file
data = pd.read_csv('derm.csv')

# Assuming the last column contains the class labels and the rest are features
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Step 2: Handle Missing Values (if any)
X = X.fillna(X.mean())  # Replace missing values with the mean of the column

# Random Train/Test Split (70%/30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)

# Step 3: Train the Naïve Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

# Step 4: Predict and Evaluate using Naïve Bayes
nb_y_pred = nb_classifier.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_y_pred)
nb_f1 = f1_score(y_test, nb_y_pred, average='weighted')

print("Naïve Bayes Results:")
print(f"Accuracy: {nb_accuracy:.3f}")
print(f"F1-score: {nb_f1:.3f}")

# Step 5: Train the Support Vector Machine Classifier
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

# Step 6: Predict and Evaluate using SVM
svm_y_pred = svm_classifier.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_y_pred)
svm_f1 = f1_score(y_test, svm_y_pred, average='weighted')

print("\nSupport Vector Machine (SVM) Results:")
print(f"Accuracy: {svm_accuracy:.3f}")
print(f"F1-score: {svm_f1:.3f}")

# Step 7: 10-fold Cross Validation
k = 10  # Number of folds for cross-validation

# Naïve Bayes cross-validation
nb_scores = cross_val_score(nb_classifier, X, y, cv=k, scoring='f1_weighted')
nb_avg_f1 = np.mean(nb_scores)
nb_avg_accuracy = np.mean(cross_val_score(nb_classifier, X, y, cv=k))

# SVM cross-validation
svm_scores = cross_val_score(svm_classifier, X, y, cv=k, scoring='f1_weighted')
svm_avg_f1 = np.mean(svm_scores)
svm_avg_accuracy = np.mean(cross_val_score(svm_classifier, X, y, cv=k))

print("\nCross-Validation Results (10-fold):")
print("Naïve Bayes")
print(f"Average Accuracy: {nb_avg_accuracy:.3f}")
print(f"Average F1-score: {nb_avg_f1:.3f}")

print("\nSupport Vector Machine (SVM)")
print(f"Average Accuracy: {svm_avg_accuracy:.3f}")
print(f"Average F1-score: {svm_avg_f1:.3f}")


Naïve Bayes Results:
Accuracy: 0.873
F1-score: 0.848

Support Vector Machine (SVM) Results:
Accuracy: 0.700
F1-score: 0.619

Cross-Validation Results (10-fold):
Naïve Bayes
Average Accuracy: 0.877
Average F1-score: 0.853

Support Vector Machine (SVM)
Average Accuracy: 0.730
Average F1-score: 0.670
