In [23]:
import pandas as pd,scipy,numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
ds = pd.read_excel(r"Job_Scheduling.xlsx")
x = ds.iloc[:,0:4].values
y = ds.iloc[:,4].values

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy="mean")
X = imp.fit_transform(x)
Y = y.reshape(-1,1)
Y = imp.fit_transform(Y)
Y = Y.reshape(-1)
print(Y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X[0,1].reshape(-1,1))
np.set_printoptions(precision=2)
X[:,1] = rescaledX.reshape(1,-1)
print(X[:,1])

In [ ]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X)
normalizedx = scaler.transform(X)
normalizedx

A manual component to machine learning, consists of preprocessing data to a form acceptable to
#### b) algorithm

k-NN algorithm does more computation on test time rather than train time.
#### b) False

Which of the following application is true about k-NN algorithm?
#### c) Both a and b

Which of the following distance measure do we use in case of categorical variables in k-NN?
#### a) Hamming Distance

Which of the following will be Manhattan Distance between the two data point A(1,3) and
B(2,3)?
#### a) 1

### Task 2

In [7]:
df = pd.read_csv(r'Iris.csv')

In [8]:
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [9]:
print(df.shape)

(150, 6)


In [10]:
print(df.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object


In [11]:
print(df.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000


In [12]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

In [13]:
lebal_encoder = LabelEncoder()
y = lebal_encoder.fit_transform(y)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=100)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

### Task 3

In [22]:
neighbors = [2,4,6,8,10]

accuracy_scores = {}

for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    
    knn.fit(X_train,y_train)
    
    y_prediction = knn.predict(X_test)
    
    accuracy = accuracy_score(y_test,y_prediction)
    accuracy_scores[k] = accuracy
    
for k,accuracy in accuracy_scores.items():
    print(f"Number of neighbor: {k}, Accuracy: {accuracy}")

Number of neighbor: 2, Accuracy: 0.88
Number of neighbor: 4, Accuracy: 0.88
Number of neighbor: 6, Accuracy: 0.8933333333333333
Number of neighbor: 8, Accuracy: 0.8933333333333333
Number of neighbor: 10, Accuracy: 0.8666666666666667


### Task 4

In [24]:
df = pd.read_csv(r'derm.csv')

In [25]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [27]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_prediction = knn.predict(X_test)
cm = confusion_matrix(y_test,y_prediction)
print("Confusion Matrix:")
print(cm)

cr = classification_report(y_test, y_prediction)
print("Classification Report:")
print(cr)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [29]:
# Perform 10-fold cross-validation
cv_scores = cross_val_score(knn, x, y, cv=10)

# Display the cross-validation scores
print("Cross-Validation Scores:")
print(cv_scores)
print("Mean Accuracy:", cv_scores.mean())

Cross-Validation Scores:
[1.         0.93333333 1.         0.93333333 0.86666667 1.
 0.93333333 1.         1.         1.        ]
Mean Accuracy: 0.9666666666666666
